apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: dev
spec:
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: "wil42/playground:v1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: svc-site
  labels:
    run: svc-site
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: site